# all paths are relative to this file

# paths
output_path: './'

# providers from which to search (case insensitive)
providers:
  - 'Indeed'
  - 'Monster'
  - 'GlassDoor'

# filters
search_terms:
  region:
    province: ''
    city:     'New York'
    domain:   'com'
    radius:   300

  keywords:
    - 'c++'
    - 'engineer'

black_list:
  - 'Infox Consulting'
  - 'Terminal'


# logging level options are: critical, error, warning, info, debug, notset
log_level: 'info'

# The oldest number of days a job can be. To disbable this option set value to -1
threshold_days: 10
# saves duplicates removed by tfidf filter to duplicate_list.csv
save_duplicates: False

# delaying algorithm configuration
delay_config:
    # functions used for delaying algorithm, options are: constant, linear, sigmoid
    function: 'linear'
    # maximum delay/upper bound for converging random delay
    delay: 10
    # minimum delay/lower bound for random delay
    min_delay: 1
    # random delay
    random: True
    # converging random delay, only used if 'random' is set to True
    converge: True
